version: '2'
services:
    ravikumargujjula-app:
        image: ravikumargujjula
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ravikumargujjula-postgresql:5432/RavikumarGujjula
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ravikumargujjula-postgresql:
        extends:
            file: postgresql.yml
            service: ravikumargujjula-postgresql
